url: https://blog.regexowl.com
title: "On a rocky road to tech"
name: 'regexowl'
locale: "en-GB"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
 
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "contrast" # "air", "aqua", "default", "dark", "dirt", "neon", "mint", "plum" "sunrise"
breadcrumbs: false
paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name     : "regexowl"
  avatar   : "/assets/profile-photo.jpg"
  bio      : "I left marketing to find my place in tech. Wish me luck, for I have not a slight idea what I am doing."
  location : "Utrecht, NL" 
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/regexowl"    
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/regexowl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/klarasimickova"

# analytics:
#  provider: "google-gtag"
#  google:
#    tracking_id: "UA-53402824-1"

include: 
    - _pages

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/regexowl"    
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/regexowl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/klarasimickova"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
author_profile: true
related: false
